### ISSUE TITLE
Any Plans to support ALE (https://github.com/w0rp/ale)

### ISSUE THREAD

**Issue by jeffrey-l-turner** [wfleming/vim-codeclimate#8]
I'm a big Neovim user and just recently received a mandate in our organization to use Codeclimate. Is there any plans to support ALE? The current quickfix window approach is slow and doesn't easily allow me to spot problems within the window.

**Comment by wfleming** [comment]
Hi @jeffrey-l-turner,

I don't have any plans to build this out myself, sorry, but I'm happy to review a PR if you'd like to work on it. 

I will say that my personal preference is towards minimalism & no dependencies, so if this plugin was going to support ALE I would want it to be an optional feature so that this plugin could *support* ALE but not *require* it. Ultimately, I suspect the amount of code to integrate with ALE might justify implementing this as a separate vim plugin instead of as part of this one. But not being very familiar with ALE perhaps I'm wrong, and if you think the functionality belongs here I'm happy to consider that.
